Create Table categories and Table products

---------------------------------------------------------------------------
CREATE TABLE categories (
    id  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(30) NOT NULL UNIQUE,
    description text,
    status varchar(10) NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'inactive')),
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP

)

----------------------------------------------------------------------------
CREATE TABLE products(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    category_id integer REFERENCES categories(id),

    name varchar(100) NOT NULL,

    sku varchar(50) NOT NULL UNIQUE,

    description text,

    unit_price numeric(12,2) NOT NULL DEFAULT 0
        CHECK(unit_price >= 0),

    quantity_in_stock integer NOT NULL DEFAULT 0
        CHECK (quantity_in_stock >= 0),

   
    reorder_level integer NOT NULL DEFAULT 10
        CHECK (reorder_level >= 0),

    status varchar(10) NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'inactive')),

    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
